sudo: required

language: php

services:
  - docker

before_install:
  - cp config/.env-dist config/.env
  - cp tests/.env-dist tests/.env
  - composer install --prefer-dist

script:
  - cd tests
  - docker-compose run forrest run